"""initial

Revision ID: ed5174599a01
Revises: 
Create Date: 2025-12-10 20:26:54.759479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5174599a01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_id'))

    op.drop_table('portfolios')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_id'))

    op.drop_table('holdings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticker', sa.VARCHAR(), nullable=False),
    sa.Column('alias', sa.VARCHAR(), nullable=True),
    sa.Column('quantity', sa.FLOAT(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('portfolio_id', sa.INTEGER(), nullable=True),
    sa.Column('average_cost', sa.FLOAT(), nullable=True),
    sa.Column('purchase_date', sa.VARCHAR(), nullable=True),
    sa.Column('account', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_id'), ['id'], unique=False)

    op.create_table('portfolios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('cash', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_id'), ['id'], unique=False)

    op.drop_table('jobs')
    # ### end Alembic commands ###
